- name: Setup Wireguard VPN Client
  hosts: vpnclients
  remote_user: ubuntu
  # Every single command in this playbook requires root privileges.
  become: true
  vars:
    timezone: America/Sao_Paulo
    # Only run "apt update && apt upgrade" if the last update is older than 24*60*60 seconds.
    cache_valid_time: 86400

  tasks:
    - name: Update apt packages
      ansible.builtin.apt:
        upgrade: false
        update_cache: true
        cache_valid_time: "{{ cache_valid_time | int }}"

    - name: Set the timezone to {{ timezone | quote }}
      community.general.timezone:
        name: "{{ timezone | quote }}"

    - name: Install Wireguard 1.0
      ansible.builtin.apt:
        name: wireguard=1.0*
        install_recommends: false

    - name: Generate key pair, Part 1
      ansible.builtin.shell:
        cmd: |
          wg genkey | sudo tee /etc/wireguard/private.key
        creates: /etc/wireguard/private.key

    - name: Generate key pair, Part 2
      ansible.builtin.shell:
        # Always run. The public key is based on the private key anyway.
        cmd: |
          sudo chmod go= /etc/wireguard/private.key
          sudo cat /etc/wireguard/private.key | wg pubkey | sudo tee /etc/wireguard/public.key

    - name: Create client configuration file
      ansible.builtin.shell:
        cmd: |
          echo "\
          [Interface]
          PrivateKey = $(sudo cat /etc/wireguard/private.key)
          # Incrementing addresses by 1 each time you add a peer is generally the easiest way to allocate IPs.
          Address = {{ hostvars[inventory_hostname]['peer_vpn_ip'] | quote }}
          SaveConfig = true
          " | sudo tee /etc/wireguard/wg0.conf

    - name: Configure wg-quick to start on boot
      ansible.builtin.shell:
        # Always run. It makes no difference if it is already running.
        cmd: |
          sudo systemctl enable wg-quick@wg0.service
          sudo systemctl start wg-quick@wg0.service
